version: '2'
services:
  surirobot-redis:
    image: redis:alpine
    restart: always

  surirobot-mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: suricats
      MYSQL_USER: surirobot
      MYSQL_PASSWD: alpine
      MYSQL_DATABASE: surirobot

  surirobot-module-facerecognition:
    image: surirobot/face-recognition
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - ./data/pictures:/root/facerecognition/pictures:rw
    environment:
      - SURIROBOT_REDIS_ADDRESS=surirobot-redis
      - MYSQL_ROOT_PASSWORD=suricats

      - FACERECO_REDIS_MODULE_NAME=face-recognition
      - FACERECO_IMG_NAME=face-640.jpg
      - FACERECO_TOLERANCE=0.54

      - SURIROBOT_DB_ADDRESS=surirobot-mariadb
      - SURIROBOT_DB_LOGIN=surirobot
      - SURIROBOT_DB_PASSWD=alpine
      - SURIROBOT_DB_NAME=surirobot

  surirobot-client:
    image: surirobot/client-qt
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./data/pictures:/root/facerecognition/pictures:rw
    environment:
      - DISPLAY=unix:0
      - SURIROBOT_REDIS_ADDRESS=surirobot-redis
