version: '2'
services:
  surirobot-redis:
    image: redis:alpine
    restart: always

  surirobot-module-facerecognition:
    image: surirobot/face-recognition
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - ./data:/root/facerecognition/data:rw
    environment:
      - SURIROBOT_REDIS_ADDRESS=surirobot-redis
      - MYSQL_ROOT_PASSWORD=suricats

      - FACERECO_REDIS_MODULE_NAME=face-recognition
      - FACERECO_IMG_NAME=face-640.jpg
      - FACERECO_TOLERANCE=0.54

      - SURIROBOT_DB=sqlite:///../data/surirobot.db

  surirobot-client:
    image: surirobot/client-qt
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/video0:/dev/video0"
      - "/dev/snd:/dev/snd"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./data:/root/facerecognition/data:rw
    environment:
      - DISPLAY=unix:0
      - SURIROBOT_REDIS_ADDRESS=surirobot-redis
